config/routes.rb
Rails.application.routes.draw do
  resources :taunts

end

app/models/taunt.rb
class Taunt < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/taunts_controller.rb
class TauntsController < ApplicationController
  before_action :set_taunt, only: [:show, :edit, :update, :destroy]

  # GET /taunts
  # GET /taunts.json
  def index
    @taunts = Taunt.all
  end

  # GET /taunts/1
  # GET /taunts/1.json
  def show
  end

  # GET /taunts/new
  def new
    @taunt = Taunt.new
  end

  # GET /taunts/1/edit
  def edit
  end

  # POST /taunts
  # POST /taunts.json
  def create
    @taunt = Taunt.new(taunt_params)

    respond_to do |format|
      if @taunt.save
        format.html { redirect_to @taunt, notice: 'Taunt was successfully created.' }
        format.json { render :show, status: :created, location: @taunt }
      else
        format.html { render :new }
        format.json { render json: @taunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taunts/1
  # PATCH/PUT /taunts/1.json
  def update
    respond_to do |format|
      if @taunt.update(taunt_params)
        format.html { redirect_to @taunt, notice: 'Taunt was successfully updated.' }
        format.json { render :show, status: :ok, location: @taunt }
      else
        format.html { render :edit }
        format.json { render json: @taunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taunts/1
  # DELETE /taunts/1.json
  def destroy
    @taunt.destroy
    respond_to do |format|
      format.html { redirect_to taunts_url, notice: 'Taunt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taunt
      @taunt = Taunt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taunt_params
      params.require(:taunt).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/taunts_helper.rb
module TauntsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Punni</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/taunts/_form.html.erb
<%= form_for(@taunt) do |f| %>
  <% if @taunt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taunt.errors.count, "error") %> prohibited this taunt from being saved:</h2>

      <ul>
      <% @taunt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taunts/edit.html.erb
<h1>Editing taunt</h1>

<%= render 'form' %>

<%= link_to 'Show', @taunt %> |
<%= link_to 'Back', taunts_path %>

app/views/taunts/index.html.erb
<h1>Listing taunts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taunts.each do |taunt| %>
      <tr>
        <td><%= taunt.name %></td>
        <td><%= taunt.content %></td>
        <td><%= link_to 'Show', taunt %></td>
        <td><%= link_to 'Edit', edit_taunt_path(taunt) %></td>
        <td><%= link_to 'Destroy', taunt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taunt', new_taunt_path %>

app/views/taunts/new.html.erb
<h1>New taunt</h1>

<%= render 'form' %>

<%= link_to 'Back', taunts_path %>

app/views/taunts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @taunt.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @taunt.content %>
</p>

<%= link_to 'Edit', edit_taunt_path(@taunt) %> |
<%= link_to 'Back', taunts_path %>